// crates/desktop-toolkit/src/lib.rs
//
// Published framework library for chamber-19 desktop tools.
//
// Consumers add this to their Cargo.toml:
//
//   [dependencies]
//   desktop-toolkit = { git = "https://github.com/chamber-19/desktop-toolkit", tag = "v2.1.0" }
//
// Then in their src/lib.rs:
//
//   use desktop_toolkit::{splash, updater, sidecar};
//
//   fn start_update(app: tauri::AppHandle, state: tauri::State<updater::UpdateState>) {
//       updater::start_update(app, state, "my-tool-backend");
//   }
//
// No ${TOOL_*} placeholders — all tool-specific values are passed at runtime.

// litcrypt2: encrypts string literals at compile time so they do not appear
// as readable strings in the release binary.  Use lc!("value") around any
// sensitive string literal.  The key below is NOT secret — it is the XOR
// cipher key for the lc!() macro; the actual secrets live in the
// XOR-obfuscated byte arrays generated by build.rs.
extern crate alloc;
#[macro_use]
extern crate litcrypt2;
use_litcrypt!("ch19-desktop-toolkit");

pub mod activation;
pub mod log;
pub mod sidecar;
pub mod splash;
pub mod updater;
