// crates/desktop-toolkit/src/activation/mod.rs
//
// Public API for the machine-bound PIN activation system.
//
// Consumer apps register the Tauri commands from `commands.rs` and
// drop `ActivationGate` from the JS package around their app root.

pub mod commands;
mod drive;
mod machine;
mod token;

use tauri::AppHandle;

pub use token::{ACTIVATION_GRACE_DAYS, ACTIVATION_WARN_DAYS};

// ── Build-time obfuscated secrets ─────────────────────────────────────────
//
// Four byte arrays generated by build.rs (XOR-obfuscated from env vars).
// The plaintext values do not appear as strings in the binary.

include!(concat!(env!("OUT_DIR"), "/activation_secrets.rs"));

pub(super) fn drive_file_id() -> String {
    _deobfuscate(DRIVE_FILE_ID_ENC)
}

pub(super) fn drive_api_key() -> String {
    _deobfuscate(DRIVE_API_KEY_ENC)
}

pub(super) fn hmac_secret() -> String {
    _deobfuscate(HMAC_SECRET_ENC)
}

pub(super) fn pin_hash_secret() -> String {
    _deobfuscate(PIN_HASH_SECRET_ENC)
}

// ── Result type ───────────────────────────────────────────────────────────

#[derive(serde::Serialize, serde::Deserialize, Clone, Debug)]
pub struct ActivationResult {
    pub valid: bool,
    pub name: String,
    pub expires_at: String,
    /// True when within ACTIVATION_WARN_DAYS days of expiry.
    pub warning: bool,
    pub days_remaining: i64,
}

// ── Public functions ──────────────────────────────────────────────────────

/// Returns `true` when a valid, non-expired, machine-bound token exists.
///
/// No network call is made.
pub fn check_activation(app: &AppHandle) -> bool {
    token::verify_token(app).is_ok()
}

/// Validate `pin` against the Drive auth file and persist a signed local token.
///
/// This is the only function that makes a network call.
pub async fn activate_with_pin(
    app: &AppHandle,
    pin: &str,
) -> Result<ActivationResult, String> {
    if _is_empty_slot(DRIVE_FILE_ID_ENC) || _is_empty_slot(DRIVE_API_KEY_ENC) {
        return Err(lc!(
            "Activation not configured: ACTIVATION_DRIVE_FILE_ID / \
             ACTIVATION_DRIVE_API_KEY were not set at build time."
        ));
    }

    let machine_id = machine::get_machine_id()?;
    let entry = drive::lookup_pin(pin).await?;

    if !entry.active {
        return Err("PIN is revoked or inactive".to_string());
    }

    if let Some(ref expires) = entry.expires {
        if token::is_date_expired(expires) {
            return Err(format!("PIN expired on {expires}"));
        }
    }

    token::write_token(
        app,
        pin,
        &entry.name,
        &machine_id,
        entry.expires.as_deref().unwrap_or(""),
    )
}

/// Remove the local activation token (deactivates this machine).
pub fn deactivate(app: &AppHandle) -> Result<(), String> {
    token::delete_token(app)
}

/// Full activation status including warning flag and days remaining.
pub fn activation_status(app: &AppHandle) -> Result<ActivationResult, String> {
    token::token_status(app)
}
